# Generated by Django 4.1.6 on 2023-02-11 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('upated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='switch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('is_VC', models.BooleanField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_site', to='central_inventory.site')),
                ('upated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_id', models.IntegerField()),
                ('csm_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('upated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IAP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('is_VC', models.BooleanField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IAP_site', to='central_inventory.site')),
                ('upated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
